### ISSUE TITLE
Empty batch for WSC

### ISSUE THREAD

**Issue by ethanjperez** [rrmenon10/ADAPET#12]
For WSC, the Batcher sometimes produces batches of size 0. Do you have any idea why that is? In particular, on this [line](https://github.com/rrmenon10/ADAPET/blob/master/src/data/WSCReader.py#L183) in WSCReader.py, I sometimes find that `len(list_input_ids) == 0`.

I don't think this happens with the original FewGLUE WSC data, but it does happen for me on other versions of FewGLUE that I have sampled myself, for example the WSC train file below:
[train.txt](https://github.com/rrmenon10/ADAPET/files/6401230/train.txt)

I have made some additional small changes on top of the ADAPET repo, so it's possible that those changes are causing the issue, but I just wanted to check if you knew if something in the original ADAPET repo that could be causing the issue.

**Comment by rrmenon10** [comment]
We have not come across this error before. To my recollection, we did try one different split than FewGLUE (for evaluation though, not training). However, we did not encounter any errors with that before.

UPDATE: I tried the training examples you had linked. It finished 250 training batches without any issue. I had to change just one [line](https://github.com/rrmenon10/ADAPET/blob/87d521a49fd8f13d7e7ea2fca01e7166c8904882/src/data/WSCReader.py#L68) to line[:-1] to avoid the '\n'.

**Comment by ethanjperez** [comment]
Ok, thanks for trying - good to know it works for you!

When you generated the different split for FewGLUE, were there any constraints you put on the examples you selected? I.e., for WSC, only examples with the "true" label are included. I'm curious if there are other constraints like that (just so I match the right way to sample examples for ADAPET/FewGLUE). If you have the code you used for reference, that would also be helpful.

**Comment by rrmenon10** [comment]
I looked back into some of our prior experiments. It turns out we didn't try a new split for WSC. It was just BoolQ, CB, and RTE. 

I don't think there's any requirement for the examples to all have the 'true' label necessarily. The model, however, does filter out examples with the false label at this [line](https://github.com/rrmenon10/ADAPET/blob/87d521a49fd8f13d7e7ea2fca01e7166c8904882/src/data/WSCReader.py#L123).

**Comment by ethanjperez** [comment]
Good to know. Thanks!
