### ISSUE TITLE
Which patterns are used?

### ISSUE THREAD

**Issue by ethanjperez** [rrmenon10/ADAPET#13]
Does the code automatically use the single pattern that performed best on dev (used to report results in Table 1)? Also, were those patterns the ones used for the SuperGLUE test evaluation (Table 2)?

**Comment by rrmenon10** [comment]
By default, the experiments run pattern 1 as indicated by this [line](https://github.com/rrmenon10/ADAPET/blob/87d521a49fd8f13d7e7ea2fca01e7166c8904882/config/BoolQ.json#L16) in each config. This does not correspond to the best pattern for all tasks. The best pattern for each task can be found in Table 4 of the paper. The patterns highlighted in Table 4 were the ones used to report the test and validation scores on SuperGLUE.

**Comment by ethanjperez** [comment]
Okay, good to know. What is the best pattern number (i.e., for the config file) for each dataset?

**Comment by rrmenon10** [comment]
The best pattern for each task can be found in Table 4 of the [paper](https://arxiv.org/pdf/2103.11955.pdf).
