### ISSUE TITLE
ModuleNotFoundError: No module named 'src.utils.get_model'

### ISSUE THREAD

**Issue by ethanjperez** [rrmenon10/ADAPET#14]
I believe that there is a missing file "src/utils/get_model.py" which is required for model dev evaluation, referenced in this [line](https://github.com/rrmenon10/ADAPET/blob/master/src/dev.py#L8)

If I just try to run `import src.utils.get_model`, then I get the following error:
```
ModuleNotFoundError: No module named 'src.utils.get_model'
```

**Comment by rrmenon10** [comment]
I've removed the line and replaced it with the correct one. Thanks for catching this.
