### ISSUE TITLE
src/dev.py error loading model

### ISSUE THREAD

**Issue by ethanjperez** [rrmenon10/ADAPET#15]
For the model checkpoint I've saved, I'm getting an error when loading them with `src/dev.py` -- basically the `model_state_dict` field doesn't appear to exist in the `*.pt` saved model checkpoint file. The issue is caused by the line below (line number may be different in this repo):
```
Traceback (most recent call last):
  File "src/dev.py", line 35, in <module>
    model.load_state_dict(torch.load(os.path.join(args.exp_dir, checkpoint))["model_state_dict"])
KeyError: 'model_state_dict'
```

The model loads successfully if I remove `["model_state_dict"]`, but just wanted to check that that's the correct fix here.

**Comment by rrmenon10** [comment]
Thanks for the catch. The dev should be using `best_model.pt` for its evaluation rather than `cur_model.pt`. I've fixed this bug now in the code.

**Comment by ethanjperez** [comment]
If I want to evaluate the models at other checkpoints, is the right thing to do to remove `["model_state_dict"]`?

**Comment by rrmenon10** [comment]
Yes. The current codebase does not require `["model_state_dict"]`.
