### ISSUE TITLE
Can this be used for fine-tuning and predictions also or only testing and obtaining scores? If it can, how so?

### ISSUE THREAD

**Issue by ghost** [rrmenon10/ADAPET#17]
Can this be used for fine-tuning and predictions also or only testing and obtaining scores? If it can, how so? How do I make predictions with this model considering that's even possible? I managed to fill out the json files in config and ran the shell scripts but that resulted in the SuperGLUE dev and test scores along with some other stuff. I want to make my own PET model and train it on some of my data and then generate text or completions with it. How would I do this?

**Comment by rrmenon10** [comment]
Resolved through other mediums.

**Comment by BleepLogger** [comment]
What "other mediums"? I'm sorry, I don't seem to understand.
