### ISSUE TITLE
Training ADAPET on data too large to fit in RAM.

### ISSUE THREAD

**Issue by ghost** [rrmenon10/ADAPET#18]
I am training an ADAPET model on 800gb of text. However, I cannot load this data into a variable since I don't have _nearly_ enough RAM to do that. Is there any way to keep loading the data chunk-by-chunk and training it bit-by-bit? Online learning of some sorts, maybe? How to do this with an ADAPET model?

**Comment by rrmenon10** [comment]
My guess (have not tried this myself) is you could try lazy-loading your dataset using .npz files for each example as mentioned [here](https://stackoverflow.com/a/34119852/395857). This might allow you to train the model normally without having to resort to active learning. We are not sure how good ADAPET might be in an active learning / online learning setting.

**Comment by ghost** [comment]
That's helpful! Do I just keep the data in .npz format or do I actually have to make any changes to the source code?

**Comment by ghost** [comment]
I have a bunch of text files, not numpy arrays. How do I save these as npz? I'm guessing I'll have to code a custom task dataprocessor, as directed in timoschick/pet. Do I use the same format as shown in that repo for a data processor and pvp? Once I've written my processor and pvp, where do I specify them?

**Comment by rrmenon10** [comment]
You'd have to convert each text example into the .npz format and make some changes in the source code when you design the dataset reader. As far as I know, strings can be saved as .npz files without much hassle.

For the data processor, you should be able to infer what to do by looking at one of the dataset readers we've designed (for SuperGLUE) in this repo to get ADAPET running. I do not think there's a direct relation between the data processor in Timo's code and the dataset reader in our repo. If you're interested in running PET, you could redirect the question there as I'm not fully in tune with the codebase now.

**Comment by ghost** [comment]
I opened up an issue on Mr. Schick's repo. Please check. Somebody says that this(online learning with PET) is possible with DeepSpeed but this required modifying the entire codebase. Do you know anything about this?

**Comment by rrmenon10** [comment]
I do not think the issue mentioned anything about online learning. DeepSpeed sounds like it might get some improvement. However, I haven't worked with it to know how good it might be. Echoing what Timo said in the issue, it might be useful to pretrain a model (since you have such a large dataset) using another library and fine-tune it using PET/ADAPET.

**Comment by ghost** [comment]
I think I'll make the modifications to PET on my own and write a new implementation of PET by myself. Thanks though!
