### ISSUE TITLE
Any reason why MNLIReader.py was deleted?

### ISSUE THREAD

**Issue by abhilashreddys** [rrmenon10/ADAPET#21]
In the new version of the paper, MNLI results were removed. May I know what the problem is in using ADAPET on MNLI?

**Comment by rrmenon10** [comment]
In our paper, we never had results on any of the datasets outside of SuperGLUE (MNLI is not in SuperGLUE). For reference, you can access the first version of our paper [here](https://arxiv.org/abs/2103.11955v1).

**Comment by abhilashreddys** [comment]
My bad, I got confused with the PET paper.
