### ISSUE TITLE
Questions about the patterns used for training

### ISSUE THREAD

**Issue by huchinlp** [rrmenon10/ADAPET#24]
Hi,

ADAPET is impressive and thanks for sharing the code!

But I am confused about the patterns used for training.
Your code (the current branch) sets `pattern_idx` as `random` by default (in `src/utils/Config.py`), which randomly samples a PVP from the list for each batch in training and ensembles the results from all PVP in evaluation. If I understand correctly, this setting is the same as `Multi-Task Multi-Pattern Training` mentioned in your paper (C.2), which is slightly worser than ADAPET.
I have tried setting `pattern_idx` to the best PVPs described in Table 4 but the performance is much worser than the random setting.

Do you have any suggestions for reproducing the best results reported in your paper?

Thanks again!

**Comment by huchinlp** [comment]
I replaced the environment from `torch==1.5.0` to `torch==1.7.0` on an NVIDIA Titan V server and run the code smoothly.
Now I can reproduce the same or similar results on all tasks.

**Comment by rrmenon10** [comment]
That's great. We did have issues reproducing with other versions of PyTorch on our end as well with scores becoming significantly worse. This is partly the reason why we recommend installing a conda/virtualenv environment using the requirements file provided with the repository.
