### ISSUE TITLE
Train your own data

### ISSUE THREAD

**Issue by Afnan-Sultan** [rrmenon10/ADAPET#26]
Hi, 

I want to use ADAPET on my own data. So, I was trying to follow your recommendation with a toy dataset. 
I took a small subset of data/BoolQ/train.jsonl and removed the "idx" key, so it looks like my own data. 

So, the file lines look like this 
`{"question": "is ghost in the shell based on the anime", "passage": "Ghost in the Shell -- Animation studio Production I.G has produced ....", "label": false}
.
.
.
.
`

I used the command you provided in the `README.md` as follows:
`python cli.py --data_dir $data_dir --pattern '"[TEXT1]" has an answer in "[TEXT2]"? "[LBL]"' --dict_verbalizer '{"true": "yes", "false": "no"}'`

and that command throws this error:
`Traceback (most recent call last):
File "cli.py", line 52, in <module> 
train(config)
File "~/ADAPET/src/train.py", line 59, in train
batcher = Batcher(config, tokenizer, config.dataset)
File "~/ADAPET/src/data/Batcher.py", line 21, in __init__
self.dataset_reader = DatasetReader(config, tokenizer, dataset)
File "~/ADAPET/src/data/DatasetReader.py", line 44, in __init__
self.dataset_reader = GenericReader(self.config, tokenizer)
File "~/ADAPET/src/data/GenericReader.py", line 24, in __init__
self.check_pattern(self.config.pattern)
File "~/ADAPET/src/data/GenericReader.py", line 45, in check_pattern
raise ValueError("Need at least one text ")
ValueError: Need at least one text `

I would highly appreciate guiding me on what I am doing wrong.

Thank you!

**Comment by rrmenon10** [comment]
Hi @Afnan-Sultan, as mentioned in the [Train your own ADAPET section](https://github.com/rrmenon10/ADAPET#train-your-own-adapet), the keys for the input need to be formatted with keys as "TEXT1", "TEXT2", ... instead of "question", "passage", ... I believe the code should work if you reset the data samples this way. Additionally please also make sure to provide a pattern that makes use of "[TEXT1]", "[TEXT2]", ... Hope this helps!

**Comment by Afnan-Sultan** [comment]
Thank you @rrmenon10 for you response!

I did apply the doc to follow the format as provided. So, now it looks as follows:

`{"TEXT1": "is ghost in the shell based on the anime", "TEXT2": "Ghost in the Shell -- Animation studio Production I.G has produced ....", "LBL": false}
{"TEXT1": "is there gonna be a season 8 of the walking dead", "TEXT2": "The Walking Dead (season 8) -- The eighth season of The ....", "LBL": true}
`

I also changed the command as follows:

`python cli.py --data_dir $data_dir --pattern '"[TEXT1]" has an answer in "[TEXT2]"? "[LBL]"' --dict_verbalizer '{"true": "yes", "false": "no"}'`

I got the following error:
`Traceback (most recent call last):
  File "cli.py", line 52, in <module>
    train(config)
  File "~/ADAPET/src/train.py", line 92, in train
    sup_batch = next(train_iter)
  File "~/ADAPET/src/data/Batcher.py", line 99, in get_train_batch
    self._init_train()
  File "~/ADAPET/src/data/Batcher.py", line 71, in _init_train
    train_data = self.dataset_reader.read_dataset("train")
  File "~/ADAPET/src/data/DatasetReader.py", line 64, in read_dataset
    return np.asarray(self.dataset_reader.read_dataset(split, is_eval))
  File "~/ADAPET/src/data/GenericReader.py", line 99, in read_dataset
    raise ValueError("Label %s not in dictionary verbalizer" % json_string["LBL"])
ValueError: Label False not in dictionary verbalizer
`

I don't know why is this error happening or why is the code expecting that key. 
I would highly appreciate your help!

**Comment by Afnan-Sultan** [comment]
@rrmenon10 

Turned out the problem was in the data file. The values of the `LBL` key were not recognized as `str`. 
So, changing the file part `"LBL": false}` to `"LBL": "false"}`, skipped that error. 

Now, I get this error this error:
`Traceback (most recent call last):
  File "cli.py", line 52, in <module>
    train(config)
  File "~/ADAPET/src/train.py", line 93, in train
    loss, dict_val_update = model(sup_batch)
  File "~/ADAPET/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "~/ADAPET/src/adapet.py", line 213, in forward
    pet_disc_loss = self.get_decoupled_label_loss(batch)
  File "~/ADAPET/src/adapet.py", line 178, in get_decoupled_label_loss
    lbl_logits = self.get_single_logits(pet_mask_ids, mask_idx, list_lbl) # [bs, num_lbl]
  File "~/ADAPET/src/adapet.py", line 79, in get_single_logits
    pet_mask_logits = torch.matmul(mask_idx_emb[:, :, None, :], pet_logits[:, None, :, :]).squeeze(
RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:549`

**Comment by rrmenon10** [comment]
Hi @Afnan-Sultan, I thought I had replied to the previous issue with the same fix you mentioned 😅. Glad to know you were able to figure it out!

**Comment by Afnan-Sultan** [comment]
@rrmenon10 
Should I initiate a new issue then for the error I am facing now?

**Comment by rrmenon10** [comment]
Whoops, my mistake. Thought it was fixed. I’ll reopen it and attend to it soon.

**Comment by rrmenon10** [comment]
Hi @Afnan-Sultan, I think you may have to step through the code and check the size of the inputs in this case. Perhaps before line 79, if you could print the shapes of `mask_idx_emb ` and `pet_logits`, I might be able to help. Thanks!

**Comment by Afnan-Sultan** [comment]
Hi @rrmenon10, I added this line in the code `print("mask_idx_emb shape is: ", mask_idx_emb.shape, "\npet_logits shape is: ", pet_logits.shape)` and I got this result
`mask_idx_emb shape is:  torch.Size([1, 1, 256])`
`pet_logits shape is:  torch.Size([1, 256, 30000])`
`mask_idx_emb shape is:  torch.Size([1, 1, 256])`
`pet_logits shape is:  torch.Size([1, 256, 30000])`  
`mask_idx_emb shape is:  torch.Size([1, 1, 256])`
`pet_logits shape is:  torch.Size([1, 256, 30000])`
`mask_idx_emb shape is:  torch.Size([1, 1, 256])` 
`pet_logits shape is:  torch.Size([1, 274, 30000])`
`Traceback (most recent call last):`
 ` File "cli.py", line 52, in <module>`
`    train(config)`
  `File "~/ADAPET/src/train.py", line 93, in train`
   ` loss, dict_val_update = model(sup_batch)`
`  File "~/ADAPET/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__`
 `   result = self.forward(*input, **kwargs)`
`  File "~/ADAPET/src/adapet.py", line 214, in forward`
 `   pet_disc_loss = self.get_decoupled_label_loss(batch)`
 ` File "~/ADAPET/src/adapet.py", line 179, in get_decoupled_label_loss`
  `  lbl_logits = self.get_single_logits(pet_mask_ids, mask_idx, list_lbl) # [bs, num_lbl]`
`  File "~/ADAPET/src/adapet.py", line 80, in get_single_logits`
`    pet_mask_logits = torch.matmul(mask_idx_emb[:, :, None, :], pet_logits[:, None, :, :]).squeeze(`
`RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:549` 

Moreover, I tried to work with different dataset to see if the error is transferable. I got different errors for that new dataset. 
for example, I got this error 
`File "~/ADAPET/src/adapet.py", line 70, in get_single_logits`
`    lbl_ids[i, :len(i_lbl_ids)] = i_lbl_ids`
`ValueError: cannot copy sequence with size 2 to array axis with dimension 1`

I tried to make arbitrary changes to the `--dict_verbalizer` parameter, where I changed the werbalizer for some label, I got the same error in different form
`ValueError: cannot copy sequence with size 2 to array axis with dimension 1`

I did another arbitrary change -again, something that has nothing to do with the labels or the cod, just changing the verbalizer from a word to another-. I goth this new error
`File "~/ADAPET/src/adapet.py", line 78, in get_single_logits`
`    pet_logits = self.model(pet_mask_ids, (pet_mask_ids > 0).long())[0]  # [bs, max_seq_len, vocab_size]`
`File "~/ADAPET/venv/lib/python3.6/site-packages/transformers/models/albert/modeling_albert.py", line 239, in forward`
`    embeddings = inputs_embeds + position_embeddings + token_type_embeddings`
`RuntimeError: The size of tensor a (660) must match the size of tensor b (512) at non-singleton dimension 1`

It looks like there is a problem with my input data. It would be very helpful if there is a strict guide to show how to formulate the data and each parameter with different examples.

**Comment by rrmenon10** [comment]
Yes, it looks like an issue with how the input data has been tokenized for the input data. My suggestion would be to step into the src/tokenize.py file to check the point where the error occurs. If convenient, you can email the data (or the smallest possible set) that results in the bug and we can have it checked out locally.
