### ISSUE TITLE
Train ADAPET with other pretrained models

### ISSUE THREAD

**Issue by xruifan** [rrmenon10/ADAPET#29]
Hi, 

I am trying to train ADAPET with my own data. If I want to use other pretrained language models, how do I do that? Can I just change the line of pretrained_weight argument in cli.py file? 

Thanks.

**Comment by rrmenon10** [comment]
If this is for your dataset, that should be enough. However, if you try to run any SuperGLUE dataset, you may encounter errors since some of the [SEP] tokens have been hardcoded. Let me know if you have any issues! Thanks!

**Comment by xruifan** [comment]
I just tried it and it started working perfectly, thank you!
