### ISSUE TITLE
Batch number for sPET and ADAPET

### ISSUE THREAD

**Issue by xruifan** [rrmenon10/ADAPET#30]
Hi, 

in your paper you trained the sPET and ADAPET models using the same experimental setups, I wonder how did you set sPET's batch number? Setting batch number for ADAPET is straight forward, but if I remember right in [PET's code](https://github.com/timoschick/pet) they don't set up for it, by contrast, they have flags for number of train examples and train batch size, and also some settings related to numbers and batch sizes of unlabelled data. 

Fan.

**Comment by xruifan** [comment]
I just saw it in [cli.py in line 23](https://github.com/rrmenon10/ADAPET/blob/ac0964e9de0a45daa9f56279dacbb32226a16a49/cli.py#L23). It is said that `1 batch = grad_accumulation_factor x batch_size`. Assuming that I have 7712 training examples, in PET I set pet_gradient_accumulation_steps as 2 and batch_size as 4 (in terms of labelled data only). In order to train an ADAPET with the equivalent setup, I will need to set batch_number to `(7712/(2*4))*3` (pet_num_train_epochs default is 3), which is equal to `964 * 3`, right?

**Comment by rrmenon10** [comment]
Hi, yes, I think that sounds correct.
