### ISSUE TITLE
How to train with fixed masking ratio?

### ISSUE THREAD

**Issue by ethanjperez** [rrmenon10/ADAPET#7]
How do I train an ADAPET model with a fixed (as opposed to variable) masking ratio, as described in Appendix C.6 / Table 12?

**Comment by rrmenon10** [comment]
You should be able to make it fixed by setting the `upto_ratio_mask` value to 1 here: https://github.com/rrmenon10/ADAPET/blob/1777f92c31c3bea15b39fbef4bc297d00e159116/src/data/tokenize.py#L55

**Comment by ethanjperez** [comment]
Great, thank you!

**Comment by ethanjperez** [comment]
Will this change also work for COPA / other datasets? I see that later in the file (e.g., for COPA [here](https://github.com/rrmenon10/ADAPET/blob/1777f92c31c3bea15b39fbef4bc297d00e159116/src/data/tokenize.py#L67)), there are other functions for performing the masking for other datasets

**Comment by rrmenon10** [comment]
We checked our codebase again, we do not use the function `tokenize_pet_mlm_copa_txt` in this repo or the development repo used. We will remove the function promptly from the codebase to avoid any confusion. 

The results in the paper used the function `tokenize_pet_mlm_txt` as well. However, we'd like to note that the patterns used for COPA change during label conditioning as mentioned in Appendix B.2 of the [paper](https://arxiv.org/pdf/2103.11955.pdf).

**Comment by ethanjperez** [comment]
Thanks for clarifying!
