### ISSUE TITLE
Missing Hyperparameters in config files

### ISSUE THREAD

**Issue by ethanjperez** [rrmenon10/ADAPET#8]
I noticed that a few `config` files are missing some hyperparameters, so I wanted to clarify the correct values:
- Should [config/WiC.json](https://github.com/rrmenon10/ADAPET/blob/master/config/WiC.json) set `mask_alpha: 0.105`? By default, the value is set to 0.5, which I don't think matches the description in the paper (though I could be mistaken). What value was used to train the reported model in the paper?
- Should [config/BoolQ.json](https://github.com/rrmenon10/ADAPET/blob/master/config/BoolQ.json) and [config/WSC.json](https://github.com/rrmenon10/ADAPET/blob/master/config/WSC.json) set `dropout_rate: 0.1` as in the other config files? I can't find where this hyperparameter is used, so maybe it doesn't matter that the value is missing from these configs.

Thanks for your help clarifying!

**Comment by dptam** [comment]
Hi, 

Thanks for your interest. 

- Yes, all datasets use `mask_alpha=.105`, including config/WiC.json. Sorry we cleaned up our code and copied some stuff incorrectly.
-  Yes, `dropout_rate` is not used for anything. We had it for some other stuff that we removed.

**Comment by ethanjperez** [comment]
Good to know, thanks!
